name = "blogging-app"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmQyMjJjMTAtZTk2My00NGQzLWIxYWMtM2QzZjM3N2NiZmJmIiwidGVuYW50X2lkIjoiOTAzMWIyMTdlODE3ZWJjZjZhOWQzMzY5ODliYjcwMjVlYTQ1NTJmMTgyNTliNzdhYTBmYWU0ZGJiZjk3YTc4NyIsImludGVybmFsX3NlY3JldCI6IjgzZjg5MTJhLTZmZjUtNDk1MS05OGUzLTczM2I0MzNlOGRhOCJ9._PZy76zYv2mKM031NZer6cHClq3LBXigIr57LJWI9e4"
JWT_SECRET = "cosmos"